# Generated by Django 6.0.6 on 2026-06-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_email_verified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpcode",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("phone_verify", "Phone verification"),
                    ("email_verify", "Email verification"),
                ],
                default="phone_verify",
                max_length=32,
            ),
        ),
    ]
