# Generated by Django 6.0.6 on 2026-06-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_otpcode_email_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="internal_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
