# Generated by Django 6.0.6 on 2026-06-19 08:46

import core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0005_report"),
        ("suppliers", "0002_yard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("duration_days", models.PositiveIntegerField()),
                (
                    "scheme",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=16,
                    ),
                ),
                ("fee_basis", models.CharField(max_length=64)),
                ("hire_value", models.BigIntegerField()),
                ("service_fee", models.BigIntegerField()),
                ("payout_amount", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("accepted", "Accepted"),
                            ("confirmed", "Confirmed"),
                            ("on_hire", "On Hire"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("in_dispute", "In Dispute"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                (
                    "cancelled_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hirer", "Hirer"),
                            ("supplier", "Supplier"),
                            ("ops", "Ops"),
                            ("system", "System"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("decline_reason", models.CharField(blank=True, max_length=255)),
                ("cancel_reason", models.CharField(blank=True, max_length=255)),
                ("hirer_note", models.TextField(blank=True)),
                ("request_expires_at", models.DateTimeField()),
                ("payment_deadline", models.DateTimeField(blank=True, null=True)),
                ("acknowledgments", models.JSONField(blank=True, default=dict)),
                (
                    "hirer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hires_as_hirer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hires",
                        to="listings.listing",
                    ),
                ),
                (
                    "parent_hire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extensions",
                        to="hires.hire",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hires_as_supplier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "yard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hires",
                        to="suppliers.yard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HandoverRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("on_hire", "On Hire"), ("off_hire", "Off Hire")],
                        max_length=16,
                    ),
                ),
                ("photos", models.JSONField(blank=True, default=list)),
                ("reading", models.JSONField(blank=True, default=dict)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handovers_confirmed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handovers_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handovers",
                        to="hires.hire",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HireEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor_kind",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("system", "System"),
                            ("ops", "Ops"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("requested", "Requested"),
                            ("accepted", "Accepted"),
                            ("confirmed", "Confirmed"),
                            ("on_hire", "On Hire"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("in_dispute", "In Dispute"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("accepted", "Accepted"),
                            ("confirmed", "Confirmed"),
                            ("on_hire", "On Hire"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("in_dispute", "In Dispute"),
                        ],
                        max_length=16,
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hire_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="hires.hire",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="hire",
            index=models.Index(
                fields=["listing", "status", "start_date", "end_date"],
                name="hires_hire_listing_486f4e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hire",
            index=models.Index(
                fields=["hirer", "status"], name="hires_hire_hirer_i_d17b65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hire",
            index=models.Index(
                fields=["supplier", "status"], name="hires_hire_supplie_da28a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="handoverrecord",
            index=models.Index(
                fields=["hire", "kind"], name="hires_hando_hire_id_52bedc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hireevent",
            index=models.Index(
                fields=["hire", "created_at"], name="hires_hiree_hire_id_89aa86_idx"
            ),
        ),
        # Append-only at the DB level: revoke UPDATE/DELETE so the immutable
        # event log can't be rewritten. Effective when the app connects under a
        # restricted (non-superuser) role; the model layer enforces it otherwise.
        migrations.RunSQL(
            sql="REVOKE UPDATE, DELETE ON hires_hireevent FROM PUBLIC;",
            reverse_sql="GRANT UPDATE, DELETE ON hires_hireevent TO PUBLIC;",
        ),
    ]
