# Generated by Django 6.0.6 on 2026-07-12 05:07

import core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hires', '0001_initial'),
        ('listings', '0005_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=140)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability_blocks_created', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='listings.listing')),
            ],
            options={
                'indexes': [models.Index(fields=['listing', 'start_date', 'end_date'], name='hires_avail_listing_1474e0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='availability_block_dates_ordered')],
            },
        ),
    ]
