# Generated by Django 6.0.6 on 2026-07-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hires', '0002_availabilityblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverrecord',
            name='photos_purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
