# Generated by Django 6.0.6 on 2026-06-19 10:07

import core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hires", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.CharField(max_length=128, unique=True)),
                ("event_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=64, unique=True)),
                ("charge_id", models.CharField(blank=True, max_length=128)),
                ("authorization_url", models.TextField(blank=True)),
                ("amount", models.BigIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="initiated",
                        max_length=16,
                    ),
                ),
                ("attempt", models.PositiveSmallIntegerField(default=1)),
                ("channel", models.CharField(blank=True, max_length=32)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "hire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="hires.hire",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["hire", "state"], name="payments_pa_hire_id_96cc60_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.BigIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("provider_ref", models.CharField(blank=True, max_length=128)),
                ("reason", models.CharField(blank=True, max_length=64)),
                (
                    "hire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="hires.hire",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["hire", "state"], name="payments_re_hire_id_fdf35c_idx"
                    )
                ],
            },
        ),
    ]
