# Generated by Django 6.0.6 on 2026-06-19 14:34

import core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hires", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.BigIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("completion", "Completion"),
                            ("withheld_day", "Withheld day"),
                        ],
                        default="completion",
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("due", "Due"),
                            ("paid", "Paid"),
                            ("frozen", "Frozen"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("paid_ref", models.CharField(blank=True, max_length=128)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("frozen_reason", models.CharField(blank=True, max_length=64)),
                (
                    "hire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="hires.hire",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["supplier", "state"],
                        name="payments_pa_supplie_eea345_idx",
                    ),
                    models.Index(fields=["state"], name="payments_pa_state_4be7de_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hire", "kind"), name="uniq_payout_per_hire_kind"
                    )
                ],
            },
        ),
    ]
