# Generated by Django 6.0.6 on 2026-06-22 06:08

import core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReconciliationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run_at", models.DateTimeField(auto_now_add=True)),
                ("checked", models.PositiveIntegerField(default=0)),
                ("mismatch_count", models.PositiveIntegerField(default=0)),
                ("mismatches", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ("-run_at",),
            },
        ),
    ]
